export const defaultVisibility : Record<string , boolean>={
    emp_id : true ,
    first_name : true ,
    last_name : true ,
    start_date : false ,
    exit_date : false ,
    supervisor : false ,
    email : true ,
    business_unit : true ,
    employee_status : true ,
    employee_type : true ,
    payzone : true ,
    employee_classification : true ,
    termination_type : false ,
    termination_description : false,
    department_type : true ,
    division : true ,
    birthdate : false ,
    state : true ,
    job_function_desc : true ,
    gender_code : false ,
    location_code : false ,
    race : false ,
    marital_status : false ,
    performance_score : true ,
    current_employee_rating : true ,
    job_title_id : true ,
  }